### ISSUE TITLE
Boss Bar

### ISSUE THREAD

**Issue by Xaikii** [Paindar/AcademyMonster#17]
is this supposed to be like this?
![2017-03-24_19 20 13](https://cloud.githubusercontent.com/assets/25128633/24308172/447d11d0-10c7-11e7-8b71-38fdf1e7c1ac.png)

**Comment by Paindar** [comment]
Yes.Boss Bar of different Boss will show in different position. My intention is to make them not overlap.
(Althought it looks a little ugly)

**Comment by Xaikii** [comment]
![2017-04-11_19 29 43](https://cloud.githubusercontent.com/assets/25128633/24922137/7d04aec6-1eed-11e7-908b-0f8620051dea.png)
New Error with Boss Bars.
![2017-04-11_19 31 58](https://cloud.githubusercontent.com/assets/25128633/24922155/927c4688-1eed-11e7-8808-dc8c4d44f03a.png)
Like you can see Boss Bar set to hide, but shown anyways... these are regular Custom NPCs, no changes made at them, and tried to fix it(tried every button for Custom NPCs) but didnt work.

**Comment by Xaikii** [comment]
![2017-04-11_19 40 16](https://cloud.githubusercontent.com/assets/25128633/24922478/c2177e70-1eee-11e7-97aa-e6571bd42b96.png)
Continued my Plans, nice view I got there :'D

**Comment by Paindar** [comment]
AM‘s BossBar is extra designed, although it looks ugly.
So the "hide" button can't control the BossBar.
I'll make only one of these BossBar shown in next version, after my mid-term exam finished. :(
