### ISSUE TITLE
This has a serious error reporting and causes a crash of the server.

### ISSUE THREAD

**Issue by chunye666** [Paindar/AcademyMonster#33]
When I use this mod on the server(CatServer), it has a serious error and crashes. The error is reported as follows:
[error from server.txt](https://github.com/Paindar/AcademyMonster/files/6602221/error.from.server.txt)
I hope you can help me to solve this problem. I will provide you with every file you need.

**Comment by Paindar** [comment]
光看这个文件我也不知道怎么回事，有没有crash_report或者latest.log看看

**Comment by chunye666** [comment]
> 光看这个文件我也不知道怎么回事，有没有crash_report或者latest.log看看

[crash-2021-06-05_16.22.32-server.txt](https://github.com/Paindar/AcademyMonster/files/6602231/crash-2021-06-05_16.22.32-server.txt)

**Comment by Paindar** [comment]
看了一下，我也整不明白。我的建议是试试删掉别的mod看看，如果不行那还是不要加入超能力怪物吧。

**Comment by chunye666** [comment]
> 看了一下，我也整不明白。我的建议是试试删掉别的mod看看，如果不行那还是不要加入超能力怪物吧。

好的，我会告知后续结果的。
